### ISSUE TITLE
But how it works?

### ISSUE THREAD

**Issue by ghost** [PikaDude/discord.mp3#1]
**Better use discord.net or normal C#, C++, etc...**

**Comment by Ovyerus** [comment]
Are you literally stupid? discord.mp3 is the best thing to ever happen in the history of Discord API wrappers. Why would you not want a Discord bot embedded right in your MP3 file? C#, C++ and other languages are absolutely useless, and are *way* too complicated for regular people to understand. The MP3 format is globally recognised and I hope you see past your mistakes and understand that this *is* the future. Thank you for your time.


/s

**Comment by ghost** [comment]
still donʻt get it, there isnʻt even code for it to work with

**Comment by Ovyerus** [comment]
It's a binary format. All code gets converted to binary at some point down the line, therefore this works by manipulating that generated binary in a specific way. It's obviously way too advanced for someone like you, you need to be able to watch Rick & Morty in order to even comprehend the basics of how it works, and that requires an IQ of at least 400.

**Comment by ghost** [comment]
Okay thanks sir, now i understand what you mean.
